### ISSUE TITLE
esp-matter-mfg-tool not working

### ISSUE THREAD

**Issue by jsheo-at-konai** [espressif/esp-matter-tools#2]
### Checklist

- [X] Checked the issue tracker for similar issues to ensure this is not a duplicate
- [X] Read the documentation to confirm the issue is not addressed there and your configuration is set correctly
- [X] Tested with the latest version to ensure the issue hasn't been fixed

### How often does this bug occurs?

always

### Expected behavior

generate nvs partition binary or something else.

### Actual behavior (suspected bug)

Whenever I try to run "esp-matter-mfg-tool", It gave me an error message.

### Error logs or terminal output

```shell
jsheo$ esp-matter-mfg-tool -h
Traceback (most recent call last):
  File "/Users/jsheo/.espressif/python_env/idf5.4_py3.9_env/bin/esp-matter-mfg-tool", line 5, in <module>
    from sources.mfg_tool import main
  File "/Users/jsheo/.espressif/python_env/idf5.4_py3.9_env/lib/python3.9/site-packages/sources/mfg_tool.py", line 44, in <module>
    from deps.mfg_gen import generate
  File "/Users/jsheo/.espressif/python_env/idf5.4_py3.9_env/lib/python3.9/site-packages/deps/mfg_gen.py", line 14, in <module>
    import nvs_partition_gen
ModuleNotFoundError: No module named 'nvs_partition_gen'
```

### Steps to reproduce the behavior

esp-idf -> source ./export.sh
esp-matter -> source ./export.sh
pip install esp-matter-mfg-tool -h
then It gave me an error

### Project release version

latest

### System architecture

ARM 64-bit (Apple M1/M2, Raspberry Pi 4/5)

### Operating system

MacOS

### Operating system version

macOS Sequoia 15.0

### Shell

Bash

**Comment by shubhamdp** [comment]
@jsheo-at-konai latest IDF has removed the `nvs_partition_gen` and it is moved to [pypi](https://pypi.org/project/esp-idf-nvs-partition-gen/). We will push a new fix for this, will let you know once its released.

**Comment by shubhamdp** [comment]
@jsheo-at-konai fix for this is merged and can be tried out. https://pypi.org/project/esp-matter-mfg-tool/

```
python3 -m pip install --upgrade esp-matter-mfg-tool
```

**Comment by jsheo-at-konai** [comment]
@shubhamdp It works. Thank you for your prompt response.
